Fix failing unit tests by adding `junit-platform-launcher` as dependency
Probably caused by a change in the resulting dependency tree.
This fixes a `NoClassDefFoundError` that occurs when trying to run the tests